# snmp-cockpit
#
# Copyright (C) 2018-2023
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

image: android-ci-image:latest

# Packages installation before running script
before_script:
  # Setup path as android_home for moving/exporting the downloaded sdk into it
  - export ANDROID_HOME="/android-home"
  - export PATH="$PATH:${ANDROID_HOME}/cmdline-tools/cmdline-tools/bin"
  - sdkmanager --version
  - ./gradlew

# Basic android and gradle stuff
# Check linting
lintDebug:
  interruptible: true
  stage: build
  allow_failure: true
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint --build-cache --gradle-user-home cache/
  cache:
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties
    paths:
      - cache/caches/
      - cache/notifications/
      - cache/wrapper/

# Make Project
assembleDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew --build-cache --gradle-user-home cache/ assembleDebug
  artifacts:
    paths:
      - app/build/outputs/
  cache:
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties
    paths:
      - cache/caches/
      - cache/notifications/
      - cache/wrapper/

# Make release
assembleRelease:
  interruptible: true
  stage: build
  when: on_success
  only:
    refs:
      - main
      - feature/*
      - fix/*
  script:
    - ./gradlew --build-cache --gradle-user-home cache/ assembleRelease
  artifacts:
    paths:
      - app/build/outputs/
  cache:
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties
    paths:
      - cache/caches/
      - cache/notifications/
      - cache/wrapper/

# Run all tests, if any fails, interrupt the pipeline(fail it)
debugTests:
  interruptible: true
  stage: test
  script:
    - ./gradlew -Pci --build-cache --gradle-user-home cache/ --console=plain :app:testDebug
  cache:
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties
    paths:
      - cache/caches/
      - cache/notifications/
      - cache/wrapper/
