header:
  license:
    spdx-id: AGPL-3.0
    copyright-owner: Emschu emschu[aet]mailbox.org
    content: |
      snmp-cockpit
      
      Copyright (C) 2018-2023
      
      This program is free software: you can redistribute it and/or modify
      it under the terms of the GNU General Public License as published by
      the Free Software Foundation, either version 3 of the License, or
      (at your option) any later version.
      
      This program is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      GNU General Public License for more details.
      You should have received a copy of the GNU General Public License
      along with this program.  If not, see <https://www.gnu.org/licenses/>.

  paths:
    - '**'

  paths-ignore:
    - 'gitlab.yml'
    - '**/.idea/**'
    - '**/*.md'
    - 'mib/**'
    - 'docs/**'
    - '**.properties'
    - '**/**.gradle'
    - '**/**.json'
    - '**/**.pro'
    - 'app/src/main/res/drawable/ic_**'
    - 'LICENSE'
    - 'COPYING'
    - 'LICENSE-Apache-2_0.txt'
    - 'gradle/wrapper/gradle-wrapper.properties'
    - 'gradlew'
    - 'NOTICE'
    - '**/**.gitignore'
    - '**/**.licenserc.yaml'
    - '.github/**.yml'
    - '.github/**/**.yml'

  comment: on-failure

dependency:
  files:
    - go.mod
    - client/package.json