name: Validate Gradle Wrapper

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
